name: bigdata_proj
services:
  bigdata_proj_mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: bigdata_proj_mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - bigdata_proj_network
    volumes:
      - mongo_data:/data/db
      - mongo_logs:/var/log/mongodb

  bigdata_proj_mongo_express:
    image: library/mongo-express:latest
    container_name: bigdata_proj_mongo_express
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: bigdata_proj_mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS}
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    depends_on:
      - bigdata_proj_mongo
    networks:
      - bigdata_proj_network
  
  bigdata_proj_postgres:
    image: postgres:16
    container_name: bigdata_proj_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - bigdata_proj_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bigdata_proj_postgres_admin:
    image: dpage/pgadmin4:latest
    container_name: bigdata_proj_postgres_admin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_ADMIN_PASS}
    ports:
      - ${POSTGRES_ADMIN_PORT}:80
    depends_on:
      - bigdata_proj_postgres
    networks:
      - bigdata_proj_network
    configs:
      - source: pgadmin_servers
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgadmin4/pgpass
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin;
      chmod 600 /var/lib/pgadmin/pgpass;
      chown pgadmin:root /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "q

  bigdata_proj_jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: bigdata_proj_jupyter
    env_file:
      - .env
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    ports:
      - ${JUPYTER_PORT}:8888
    volumes:
      - jupyter_data:/home/jovyan/work
    networks:
      - bigdata_proj_network
    command: >
      start-notebook.sh --NotebookApp.token='${JUPYTER_TOKEN}'

networks:
  bigdata_proj_network:
    driver: bridge

volumes:
  mongo_data:
  mongo_logs:
  postgres_data:
  jupyter_data:

configs:
  pgadmin_servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "bigdata_proj_postgres",
            "Group": "Servers",
            "Host": "bigdata_proj_postgres",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "${POSTGRES_USER}",
            "SSLMode": "prefer",
            "PassFile": "/var/lib/pgadmin/pgpass"
          }
        }
      }
  pgpass:
    content: |
      bigdata_proj_postgres:5432:postgres:${POSTGRES_USER}:${POSTGRES_PASS}