name: bigdata.proj
services:
  bigdata.proj.mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: bigdata.proj.mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - bigdata.proj.network
    volumes:
      - mongodata:/data/db
      - mongologs:/var/log/mongodb

  bigdata.proj.mongo.express:
    image: library/mongo-express:latest
    container_name: bigdata.proj.mongo.express
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: bigdata.proj.mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS}
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    depends_on:
      - bigdata.proj.mongo
    networks:
      - bigdata.proj.network

  bigdata.proj.jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: bigdata.proj.jupyter
    env_file:
      - .env
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    ports:
      - ${JUPYTER_PORT}:8888
    volumes:
      - ${PWD}\data:/home/jovyan/work/data
      - ${PWD}\datalake:/home/jovyan/work/datalake
      - ${PWD}\program.py:/home/jovyan/work/program.py
    networks:
      - bigdata.proj.network
    command: >
      start-notebook.sh --NotebookApp.token='${JUPYTER_TOKEN}'

  bigdata.proj.spark.master:
    image: bitnami/spark:latest
    container_name: bigdata.proj.spark.master
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_MASTER_USERNAME: ${SPARK_MASTER_USERNAME}
      SPARK_MASTER_PASSWORD: ${SPARK_MASTER_PASSWORD}
    env_file:
      - .env
    ports:
      - ${SPARK_PORT}:8080
    networks:
      - bigdata.proj.network

  bigdata.proj.spark.worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://bigdata.proj.spark.master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    env_file:
      - .env
    deploy:
      replicas: ${SPARK_WORKER_COUNT}
    depends_on:
      - bigdata.proj.spark.master
    networks:
      - bigdata.proj.network

  bigdata.proj.elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: bigdata.proj.elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.http.ssl.enabled: false
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    networks:
      - bigdata.proj.network

  bigdata.proj.kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: bigdata.proj.kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://bigdata.proj.elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_USERNAME=${KIBANA_USERNAME}
      - xpack.security.http.ssl.enabled=false
    ports:
      - ${KIBANA_PORT}:5601
    depends_on:
      - bigdata.proj.elasticsearch
    networks:
      - bigdata.proj.network

networks:
  bigdata.proj.network:
    driver: bridge

volumes:
  mongodata:
  mongologs:
  elasticdata: