name: bigdata_proj
services:
  bigdata_proj_mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: bigdata_proj_mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - bigdata_proj_network
    volumes:
      - mongo_data:/data/db
      - mongo_logs:/var/log/mongodb

  bigdata_proj_mongo_express:
    image: library/mongo-express:latest
    container_name: bigdata_proj_mongo_express
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: bigdata_proj_mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS}
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    depends_on:
      - bigdata_proj_mongo
    networks:
      - bigdata_proj_network

  bigdata_proj_jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: bigdata_proj_jupyter
    env_file:
      - .env
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    ports:
      - ${JUPYTER_PORT}:8888
    volumes:
      - jupyter_data:/home/jovyan/work
    networks:
      - bigdata_proj_network
    command: >
      start-notebook.sh --NotebookApp.token='${JUPYTER_TOKEN}'

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_MASTER_USERNAME: ${SPARK_MASTER_USERNAME}
      SPARK_MASTER_PASSWORD: ${SPARK_MASTER_PASSWORD}
    env_file:
      - .env
    ports:
      - ${SPARK_PORT}:8080
      - '7077:7077'
    networks:
      - bigdata_proj_network

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    env_file:
      - .env
    deploy:
      replicas: ${SPARK_WORKER_COUNT}
    depends_on:
      - spark-master
    networks:
      - bigdata_proj_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.http.ssl.enabled: false
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - bigdata_proj_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana-server5
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_USERNAME=${KIBANA_USERNAME}
      - xpack.security.http.ssl.enabled=false
    ports:
      - ${KIBANA_PORT}:5601
    depends_on:
      - elasticsearch
    networks:
      - bigdata_proj_network

networks:
  bigdata_proj_network:
    driver: bridge

volumes:
  mongo_data:
  mongo_logs:
  jupyter_data:
  elastic_data: