name: bigdata_proj
services:
  bigdata_proj_mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: bigdata_proj_mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - bigdata_proj_network
    volumes:
      - mongo_data:/data/db
      - mongo_logs:/var/log/mongodb

  bigdata_proj_mongo_express:
    image: library/mongo-express:latest
    container_name: bigdata_proj_mongo_express
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: bigdata_proj_mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS}
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    depends_on:
      - bigdata_proj_mongo
    networks:
      - bigdata_proj_network

  bigdata_proj_jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: bigdata_proj_jupyter
    env_file:
      - .env
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    ports:
      - ${JUPYTER_PORT}:8888
    volumes:
      - jupyter_data:/home/jovyan/work
    networks:
      - bigdata_proj_network
    command: >
      start-notebook.sh --NotebookApp.token='${JUPYTER_TOKEN}'

networks:
  bigdata_proj_network:
    driver: bridge

volumes:
  mongo_data:
  mongo_logs:
  jupyter_data: